version: "3.7"
networks:
  shilingi:
services:
  app-engine:
    container_name: app-engine
    image: localhost:5000/app-engine:${APP_ENGINE_VERSION:-v0.0.1}
    build:
      context: .
    volumes:
      - ./shilingi.db:/usr/bin/shilingi.db:rw
    environment:
      # DB_URI: mysql://zva5rzr6ftk3:pscale_pw_PrvLfFOiDyq4OLwPHSqy5j3hoInhtVSideodBb5W_bA@tcp(kvw7zun0y7sm.us-east-4.psdb.cloud)/shilingi?sslaccept=strict&tls=skip-verify
      DB_URI: file:shilingi.db?mode=rwc&_fk=1&cache=shared
      DB_TYPE: sqlite3
    ports:
      - '8080:8080'
    networks:
      - shilingi
