// Code generated by entc, DO NOT EDIT.

package account

import (
	"time"
)

const (
	// Label holds the string label denoting the account type in the database.
	Label = "account"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeMembers holds the string denoting the members edge name in mutations.
	EdgeMembers = "members"
	// EdgeInvites holds the string denoting the invites edge name in mutations.
	EdgeInvites = "invites"
	// Table holds the table name of the account in the database.
	Table = "accounts"
	// MembersTable is the table that holds the members relation/edge.
	MembersTable = "account_members"
	// MembersInverseTable is the table name for the AccountMember entity.
	// It exists in this package in order to avoid circular dependency with the "accountmember" package.
	MembersInverseTable = "account_members"
	// MembersColumn is the table column denoting the members relation/edge.
	MembersColumn = "account_members"
	// InvitesTable is the table that holds the invites relation/edge.
	InvitesTable = "account_invites"
	// InvitesInverseTable is the table name for the AccountInvite entity.
	// It exists in this package in order to avoid circular dependency with the "accountinvite" package.
	InvitesInverseTable = "account_invites"
	// InvitesColumn is the table column denoting the invites relation/edge.
	InvitesColumn = "account_invites"
)

// Columns holds all SQL columns for account fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
)
