// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kingzbauer/shilingi/app-engine/ent/accountmember"
	"github.com/kingzbauer/shilingi/app-engine/ent/predicate"
)

// AccountMemberDelete is the builder for deleting a AccountMember entity.
type AccountMemberDelete struct {
	config
	hooks    []Hook
	mutation *AccountMemberMutation
}

// Where appends a list predicates to the AccountMemberDelete builder.
func (amd *AccountMemberDelete) Where(ps ...predicate.AccountMember) *AccountMemberDelete {
	amd.mutation.Where(ps...)
	return amd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (amd *AccountMemberDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(amd.hooks) == 0 {
		affected, err = amd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AccountMemberMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			amd.mutation = mutation
			affected, err = amd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(amd.hooks) - 1; i >= 0; i-- {
			if amd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = amd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, amd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (amd *AccountMemberDelete) ExecX(ctx context.Context) int {
	n, err := amd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (amd *AccountMemberDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: accountmember.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: accountmember.FieldID,
			},
		},
	}
	if ps := amd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, amd.driver, _spec)
}

// AccountMemberDeleteOne is the builder for deleting a single AccountMember entity.
type AccountMemberDeleteOne struct {
	amd *AccountMemberDelete
}

// Exec executes the deletion query.
func (amdo *AccountMemberDeleteOne) Exec(ctx context.Context) error {
	n, err := amdo.amd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{accountmember.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (amdo *AccountMemberDeleteOne) ExecX(ctx context.Context) {
	amdo.amd.ExecX(ctx)
}
