// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/kingzbauer/shilingi/app-engine/ent/migrate"

	"github.com/kingzbauer/shilingi/app-engine/ent/account"
	"github.com/kingzbauer/shilingi/app-engine/ent/accountinvite"
	"github.com/kingzbauer/shilingi/app-engine/ent/accountmember"
	"github.com/kingzbauer/shilingi/app-engine/ent/item"
	"github.com/kingzbauer/shilingi/app-engine/ent/shopping"
	"github.com/kingzbauer/shilingi/app-engine/ent/shoppingitem"
	"github.com/kingzbauer/shilingi/app-engine/ent/shoppinglist"
	"github.com/kingzbauer/shilingi/app-engine/ent/shoppinglistitem"
	"github.com/kingzbauer/shilingi/app-engine/ent/sublabel"
	"github.com/kingzbauer/shilingi/app-engine/ent/tag"
	"github.com/kingzbauer/shilingi/app-engine/ent/user"
	"github.com/kingzbauer/shilingi/app-engine/ent/vendor"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Account is the client for interacting with the Account builders.
	Account *AccountClient
	// AccountInvite is the client for interacting with the AccountInvite builders.
	AccountInvite *AccountInviteClient
	// AccountMember is the client for interacting with the AccountMember builders.
	AccountMember *AccountMemberClient
	// Item is the client for interacting with the Item builders.
	Item *ItemClient
	// Shopping is the client for interacting with the Shopping builders.
	Shopping *ShoppingClient
	// ShoppingItem is the client for interacting with the ShoppingItem builders.
	ShoppingItem *ShoppingItemClient
	// ShoppingList is the client for interacting with the ShoppingList builders.
	ShoppingList *ShoppingListClient
	// ShoppingListItem is the client for interacting with the ShoppingListItem builders.
	ShoppingListItem *ShoppingListItemClient
	// SubLabel is the client for interacting with the SubLabel builders.
	SubLabel *SubLabelClient
	// Tag is the client for interacting with the Tag builders.
	Tag *TagClient
	// User is the client for interacting with the User builders.
	User *UserClient
	// Vendor is the client for interacting with the Vendor builders.
	Vendor *VendorClient
	// additional fields for node api
	tables tables
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Account = NewAccountClient(c.config)
	c.AccountInvite = NewAccountInviteClient(c.config)
	c.AccountMember = NewAccountMemberClient(c.config)
	c.Item = NewItemClient(c.config)
	c.Shopping = NewShoppingClient(c.config)
	c.ShoppingItem = NewShoppingItemClient(c.config)
	c.ShoppingList = NewShoppingListClient(c.config)
	c.ShoppingListItem = NewShoppingListItemClient(c.config)
	c.SubLabel = NewSubLabelClient(c.config)
	c.Tag = NewTagClient(c.config)
	c.User = NewUserClient(c.config)
	c.Vendor = NewVendorClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:              ctx,
		config:           cfg,
		Account:          NewAccountClient(cfg),
		AccountInvite:    NewAccountInviteClient(cfg),
		AccountMember:    NewAccountMemberClient(cfg),
		Item:             NewItemClient(cfg),
		Shopping:         NewShoppingClient(cfg),
		ShoppingItem:     NewShoppingItemClient(cfg),
		ShoppingList:     NewShoppingListClient(cfg),
		ShoppingListItem: NewShoppingListItemClient(cfg),
		SubLabel:         NewSubLabelClient(cfg),
		Tag:              NewTagClient(cfg),
		User:             NewUserClient(cfg),
		Vendor:           NewVendorClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		config:           cfg,
		Account:          NewAccountClient(cfg),
		AccountInvite:    NewAccountInviteClient(cfg),
		AccountMember:    NewAccountMemberClient(cfg),
		Item:             NewItemClient(cfg),
		Shopping:         NewShoppingClient(cfg),
		ShoppingItem:     NewShoppingItemClient(cfg),
		ShoppingList:     NewShoppingListClient(cfg),
		ShoppingListItem: NewShoppingListItemClient(cfg),
		SubLabel:         NewSubLabelClient(cfg),
		Tag:              NewTagClient(cfg),
		User:             NewUserClient(cfg),
		Vendor:           NewVendorClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Account.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Account.Use(hooks...)
	c.AccountInvite.Use(hooks...)
	c.AccountMember.Use(hooks...)
	c.Item.Use(hooks...)
	c.Shopping.Use(hooks...)
	c.ShoppingItem.Use(hooks...)
	c.ShoppingList.Use(hooks...)
	c.ShoppingListItem.Use(hooks...)
	c.SubLabel.Use(hooks...)
	c.Tag.Use(hooks...)
	c.User.Use(hooks...)
	c.Vendor.Use(hooks...)
}

// AccountClient is a client for the Account schema.
type AccountClient struct {
	config
}

// NewAccountClient returns a client for the Account from the given config.
func NewAccountClient(c config) *AccountClient {
	return &AccountClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `account.Hooks(f(g(h())))`.
func (c *AccountClient) Use(hooks ...Hook) {
	c.hooks.Account = append(c.hooks.Account, hooks...)
}

// Create returns a create builder for Account.
func (c *AccountClient) Create() *AccountCreate {
	mutation := newAccountMutation(c.config, OpCreate)
	return &AccountCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Account entities.
func (c *AccountClient) CreateBulk(builders ...*AccountCreate) *AccountCreateBulk {
	return &AccountCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Account.
func (c *AccountClient) Update() *AccountUpdate {
	mutation := newAccountMutation(c.config, OpUpdate)
	return &AccountUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AccountClient) UpdateOne(a *Account) *AccountUpdateOne {
	mutation := newAccountMutation(c.config, OpUpdateOne, withAccount(a))
	return &AccountUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AccountClient) UpdateOneID(id int) *AccountUpdateOne {
	mutation := newAccountMutation(c.config, OpUpdateOne, withAccountID(id))
	return &AccountUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Account.
func (c *AccountClient) Delete() *AccountDelete {
	mutation := newAccountMutation(c.config, OpDelete)
	return &AccountDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *AccountClient) DeleteOne(a *Account) *AccountDeleteOne {
	return c.DeleteOneID(a.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *AccountClient) DeleteOneID(id int) *AccountDeleteOne {
	builder := c.Delete().Where(account.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AccountDeleteOne{builder}
}

// Query returns a query builder for Account.
func (c *AccountClient) Query() *AccountQuery {
	return &AccountQuery{
		config: c.config,
	}
}

// Get returns a Account entity by its id.
func (c *AccountClient) Get(ctx context.Context, id int) (*Account, error) {
	return c.Query().Where(account.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AccountClient) GetX(ctx context.Context, id int) *Account {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryMembers queries the members edge of a Account.
func (c *AccountClient) QueryMembers(a *Account) *AccountMemberQuery {
	query := &AccountMemberQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := a.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(account.Table, account.FieldID, id),
			sqlgraph.To(accountmember.Table, accountmember.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, account.MembersTable, account.MembersColumn),
		)
		fromV = sqlgraph.Neighbors(a.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryInvites queries the invites edge of a Account.
func (c *AccountClient) QueryInvites(a *Account) *AccountInviteQuery {
	query := &AccountInviteQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := a.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(account.Table, account.FieldID, id),
			sqlgraph.To(accountinvite.Table, accountinvite.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, account.InvitesTable, account.InvitesColumn),
		)
		fromV = sqlgraph.Neighbors(a.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *AccountClient) Hooks() []Hook {
	return c.hooks.Account
}

// AccountInviteClient is a client for the AccountInvite schema.
type AccountInviteClient struct {
	config
}

// NewAccountInviteClient returns a client for the AccountInvite from the given config.
func NewAccountInviteClient(c config) *AccountInviteClient {
	return &AccountInviteClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `accountinvite.Hooks(f(g(h())))`.
func (c *AccountInviteClient) Use(hooks ...Hook) {
	c.hooks.AccountInvite = append(c.hooks.AccountInvite, hooks...)
}

// Create returns a create builder for AccountInvite.
func (c *AccountInviteClient) Create() *AccountInviteCreate {
	mutation := newAccountInviteMutation(c.config, OpCreate)
	return &AccountInviteCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AccountInvite entities.
func (c *AccountInviteClient) CreateBulk(builders ...*AccountInviteCreate) *AccountInviteCreateBulk {
	return &AccountInviteCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AccountInvite.
func (c *AccountInviteClient) Update() *AccountInviteUpdate {
	mutation := newAccountInviteMutation(c.config, OpUpdate)
	return &AccountInviteUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AccountInviteClient) UpdateOne(ai *AccountInvite) *AccountInviteUpdateOne {
	mutation := newAccountInviteMutation(c.config, OpUpdateOne, withAccountInvite(ai))
	return &AccountInviteUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AccountInviteClient) UpdateOneID(id int) *AccountInviteUpdateOne {
	mutation := newAccountInviteMutation(c.config, OpUpdateOne, withAccountInviteID(id))
	return &AccountInviteUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AccountInvite.
func (c *AccountInviteClient) Delete() *AccountInviteDelete {
	mutation := newAccountInviteMutation(c.config, OpDelete)
	return &AccountInviteDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *AccountInviteClient) DeleteOne(ai *AccountInvite) *AccountInviteDeleteOne {
	return c.DeleteOneID(ai.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *AccountInviteClient) DeleteOneID(id int) *AccountInviteDeleteOne {
	builder := c.Delete().Where(accountinvite.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AccountInviteDeleteOne{builder}
}

// Query returns a query builder for AccountInvite.
func (c *AccountInviteClient) Query() *AccountInviteQuery {
	return &AccountInviteQuery{
		config: c.config,
	}
}

// Get returns a AccountInvite entity by its id.
func (c *AccountInviteClient) Get(ctx context.Context, id int) (*AccountInvite, error) {
	return c.Query().Where(accountinvite.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AccountInviteClient) GetX(ctx context.Context, id int) *AccountInvite {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryAccount queries the account edge of a AccountInvite.
func (c *AccountInviteClient) QueryAccount(ai *AccountInvite) *AccountQuery {
	query := &AccountQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := ai.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(accountinvite.Table, accountinvite.FieldID, id),
			sqlgraph.To(account.Table, account.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, accountinvite.AccountTable, accountinvite.AccountColumn),
		)
		fromV = sqlgraph.Neighbors(ai.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryUser queries the user edge of a AccountInvite.
func (c *AccountInviteClient) QueryUser(ai *AccountInvite) *UserQuery {
	query := &UserQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := ai.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(accountinvite.Table, accountinvite.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, accountinvite.UserTable, accountinvite.UserColumn),
		)
		fromV = sqlgraph.Neighbors(ai.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryMember queries the member edge of a AccountInvite.
func (c *AccountInviteClient) QueryMember(ai *AccountInvite) *AccountMemberQuery {
	query := &AccountMemberQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := ai.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(accountinvite.Table, accountinvite.FieldID, id),
			sqlgraph.To(accountmember.Table, accountmember.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, accountinvite.MemberTable, accountinvite.MemberColumn),
		)
		fromV = sqlgraph.Neighbors(ai.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *AccountInviteClient) Hooks() []Hook {
	return c.hooks.AccountInvite
}

// AccountMemberClient is a client for the AccountMember schema.
type AccountMemberClient struct {
	config
}

// NewAccountMemberClient returns a client for the AccountMember from the given config.
func NewAccountMemberClient(c config) *AccountMemberClient {
	return &AccountMemberClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `accountmember.Hooks(f(g(h())))`.
func (c *AccountMemberClient) Use(hooks ...Hook) {
	c.hooks.AccountMember = append(c.hooks.AccountMember, hooks...)
}

// Create returns a create builder for AccountMember.
func (c *AccountMemberClient) Create() *AccountMemberCreate {
	mutation := newAccountMemberMutation(c.config, OpCreate)
	return &AccountMemberCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AccountMember entities.
func (c *AccountMemberClient) CreateBulk(builders ...*AccountMemberCreate) *AccountMemberCreateBulk {
	return &AccountMemberCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AccountMember.
func (c *AccountMemberClient) Update() *AccountMemberUpdate {
	mutation := newAccountMemberMutation(c.config, OpUpdate)
	return &AccountMemberUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AccountMemberClient) UpdateOne(am *AccountMember) *AccountMemberUpdateOne {
	mutation := newAccountMemberMutation(c.config, OpUpdateOne, withAccountMember(am))
	return &AccountMemberUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AccountMemberClient) UpdateOneID(id int) *AccountMemberUpdateOne {
	mutation := newAccountMemberMutation(c.config, OpUpdateOne, withAccountMemberID(id))
	return &AccountMemberUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AccountMember.
func (c *AccountMemberClient) Delete() *AccountMemberDelete {
	mutation := newAccountMemberMutation(c.config, OpDelete)
	return &AccountMemberDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *AccountMemberClient) DeleteOne(am *AccountMember) *AccountMemberDeleteOne {
	return c.DeleteOneID(am.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *AccountMemberClient) DeleteOneID(id int) *AccountMemberDeleteOne {
	builder := c.Delete().Where(accountmember.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AccountMemberDeleteOne{builder}
}

// Query returns a query builder for AccountMember.
func (c *AccountMemberClient) Query() *AccountMemberQuery {
	return &AccountMemberQuery{
		config: c.config,
	}
}

// Get returns a AccountMember entity by its id.
func (c *AccountMemberClient) Get(ctx context.Context, id int) (*AccountMember, error) {
	return c.Query().Where(accountmember.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AccountMemberClient) GetX(ctx context.Context, id int) *AccountMember {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryAccount queries the account edge of a AccountMember.
func (c *AccountMemberClient) QueryAccount(am *AccountMember) *AccountQuery {
	query := &AccountQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := am.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(accountmember.Table, accountmember.FieldID, id),
			sqlgraph.To(account.Table, account.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, accountmember.AccountTable, accountmember.AccountColumn),
		)
		fromV = sqlgraph.Neighbors(am.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryUser queries the user edge of a AccountMember.
func (c *AccountMemberClient) QueryUser(am *AccountMember) *UserQuery {
	query := &UserQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := am.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(accountmember.Table, accountmember.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, accountmember.UserTable, accountmember.UserColumn),
		)
		fromV = sqlgraph.Neighbors(am.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryInvite queries the invite edge of a AccountMember.
func (c *AccountMemberClient) QueryInvite(am *AccountMember) *AccountInviteQuery {
	query := &AccountInviteQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := am.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(accountmember.Table, accountmember.FieldID, id),
			sqlgraph.To(accountinvite.Table, accountinvite.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, accountmember.InviteTable, accountmember.InviteColumn),
		)
		fromV = sqlgraph.Neighbors(am.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *AccountMemberClient) Hooks() []Hook {
	return c.hooks.AccountMember
}

// ItemClient is a client for the Item schema.
type ItemClient struct {
	config
}

// NewItemClient returns a client for the Item from the given config.
func NewItemClient(c config) *ItemClient {
	return &ItemClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `item.Hooks(f(g(h())))`.
func (c *ItemClient) Use(hooks ...Hook) {
	c.hooks.Item = append(c.hooks.Item, hooks...)
}

// Create returns a create builder for Item.
func (c *ItemClient) Create() *ItemCreate {
	mutation := newItemMutation(c.config, OpCreate)
	return &ItemCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Item entities.
func (c *ItemClient) CreateBulk(builders ...*ItemCreate) *ItemCreateBulk {
	return &ItemCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Item.
func (c *ItemClient) Update() *ItemUpdate {
	mutation := newItemMutation(c.config, OpUpdate)
	return &ItemUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ItemClient) UpdateOne(i *Item) *ItemUpdateOne {
	mutation := newItemMutation(c.config, OpUpdateOne, withItem(i))
	return &ItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ItemClient) UpdateOneID(id int) *ItemUpdateOne {
	mutation := newItemMutation(c.config, OpUpdateOne, withItemID(id))
	return &ItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Item.
func (c *ItemClient) Delete() *ItemDelete {
	mutation := newItemMutation(c.config, OpDelete)
	return &ItemDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *ItemClient) DeleteOne(i *Item) *ItemDeleteOne {
	return c.DeleteOneID(i.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *ItemClient) DeleteOneID(id int) *ItemDeleteOne {
	builder := c.Delete().Where(item.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ItemDeleteOne{builder}
}

// Query returns a query builder for Item.
func (c *ItemClient) Query() *ItemQuery {
	return &ItemQuery{
		config: c.config,
	}
}

// Get returns a Item entity by its id.
func (c *ItemClient) Get(ctx context.Context, id int) (*Item, error) {
	return c.Query().Where(item.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ItemClient) GetX(ctx context.Context, id int) *Item {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryPurchases queries the purchases edge of a Item.
func (c *ItemClient) QueryPurchases(i *Item) *ShoppingItemQuery {
	query := &ShoppingItemQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := i.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(item.Table, item.FieldID, id),
			sqlgraph.To(shoppingitem.Table, shoppingitem.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, item.PurchasesTable, item.PurchasesColumn),
		)
		fromV = sqlgraph.Neighbors(i.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTags queries the tags edge of a Item.
func (c *ItemClient) QueryTags(i *Item) *TagQuery {
	query := &TagQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := i.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(item.Table, item.FieldID, id),
			sqlgraph.To(tag.Table, tag.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, item.TagsTable, item.TagsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(i.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QuerySublabel queries the sublabel edge of a Item.
func (c *ItemClient) QuerySublabel(i *Item) *SubLabelQuery {
	query := &SubLabelQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := i.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(item.Table, item.FieldID, id),
			sqlgraph.To(sublabel.Table, sublabel.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, item.SublabelTable, item.SublabelColumn),
		)
		fromV = sqlgraph.Neighbors(i.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryShoppingList queries the shoppingList edge of a Item.
func (c *ItemClient) QueryShoppingList(i *Item) *ShoppingListItemQuery {
	query := &ShoppingListItemQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := i.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(item.Table, item.FieldID, id),
			sqlgraph.To(shoppinglistitem.Table, shoppinglistitem.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, item.ShoppingListTable, item.ShoppingListColumn),
		)
		fromV = sqlgraph.Neighbors(i.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ItemClient) Hooks() []Hook {
	return c.hooks.Item
}

// ShoppingClient is a client for the Shopping schema.
type ShoppingClient struct {
	config
}

// NewShoppingClient returns a client for the Shopping from the given config.
func NewShoppingClient(c config) *ShoppingClient {
	return &ShoppingClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `shopping.Hooks(f(g(h())))`.
func (c *ShoppingClient) Use(hooks ...Hook) {
	c.hooks.Shopping = append(c.hooks.Shopping, hooks...)
}

// Create returns a create builder for Shopping.
func (c *ShoppingClient) Create() *ShoppingCreate {
	mutation := newShoppingMutation(c.config, OpCreate)
	return &ShoppingCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Shopping entities.
func (c *ShoppingClient) CreateBulk(builders ...*ShoppingCreate) *ShoppingCreateBulk {
	return &ShoppingCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Shopping.
func (c *ShoppingClient) Update() *ShoppingUpdate {
	mutation := newShoppingMutation(c.config, OpUpdate)
	return &ShoppingUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ShoppingClient) UpdateOne(s *Shopping) *ShoppingUpdateOne {
	mutation := newShoppingMutation(c.config, OpUpdateOne, withShopping(s))
	return &ShoppingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ShoppingClient) UpdateOneID(id int) *ShoppingUpdateOne {
	mutation := newShoppingMutation(c.config, OpUpdateOne, withShoppingID(id))
	return &ShoppingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Shopping.
func (c *ShoppingClient) Delete() *ShoppingDelete {
	mutation := newShoppingMutation(c.config, OpDelete)
	return &ShoppingDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *ShoppingClient) DeleteOne(s *Shopping) *ShoppingDeleteOne {
	return c.DeleteOneID(s.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *ShoppingClient) DeleteOneID(id int) *ShoppingDeleteOne {
	builder := c.Delete().Where(shopping.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ShoppingDeleteOne{builder}
}

// Query returns a query builder for Shopping.
func (c *ShoppingClient) Query() *ShoppingQuery {
	return &ShoppingQuery{
		config: c.config,
	}
}

// Get returns a Shopping entity by its id.
func (c *ShoppingClient) Get(ctx context.Context, id int) (*Shopping, error) {
	return c.Query().Where(shopping.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ShoppingClient) GetX(ctx context.Context, id int) *Shopping {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryItems queries the items edge of a Shopping.
func (c *ShoppingClient) QueryItems(s *Shopping) *ShoppingItemQuery {
	query := &ShoppingItemQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := s.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(shopping.Table, shopping.FieldID, id),
			sqlgraph.To(shoppingitem.Table, shoppingitem.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, shopping.ItemsTable, shopping.ItemsColumn),
		)
		fromV = sqlgraph.Neighbors(s.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryVendor queries the vendor edge of a Shopping.
func (c *ShoppingClient) QueryVendor(s *Shopping) *VendorQuery {
	query := &VendorQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := s.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(shopping.Table, shopping.FieldID, id),
			sqlgraph.To(vendor.Table, vendor.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, shopping.VendorTable, shopping.VendorColumn),
		)
		fromV = sqlgraph.Neighbors(s.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryShoppingList queries the shoppingList edge of a Shopping.
func (c *ShoppingClient) QueryShoppingList(s *Shopping) *ShoppingListQuery {
	query := &ShoppingListQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := s.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(shopping.Table, shopping.FieldID, id),
			sqlgraph.To(shoppinglist.Table, shoppinglist.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, shopping.ShoppingListTable, shopping.ShoppingListColumn),
		)
		fromV = sqlgraph.Neighbors(s.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ShoppingClient) Hooks() []Hook {
	return c.hooks.Shopping
}

// ShoppingItemClient is a client for the ShoppingItem schema.
type ShoppingItemClient struct {
	config
}

// NewShoppingItemClient returns a client for the ShoppingItem from the given config.
func NewShoppingItemClient(c config) *ShoppingItemClient {
	return &ShoppingItemClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `shoppingitem.Hooks(f(g(h())))`.
func (c *ShoppingItemClient) Use(hooks ...Hook) {
	c.hooks.ShoppingItem = append(c.hooks.ShoppingItem, hooks...)
}

// Create returns a create builder for ShoppingItem.
func (c *ShoppingItemClient) Create() *ShoppingItemCreate {
	mutation := newShoppingItemMutation(c.config, OpCreate)
	return &ShoppingItemCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ShoppingItem entities.
func (c *ShoppingItemClient) CreateBulk(builders ...*ShoppingItemCreate) *ShoppingItemCreateBulk {
	return &ShoppingItemCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ShoppingItem.
func (c *ShoppingItemClient) Update() *ShoppingItemUpdate {
	mutation := newShoppingItemMutation(c.config, OpUpdate)
	return &ShoppingItemUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ShoppingItemClient) UpdateOne(si *ShoppingItem) *ShoppingItemUpdateOne {
	mutation := newShoppingItemMutation(c.config, OpUpdateOne, withShoppingItem(si))
	return &ShoppingItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ShoppingItemClient) UpdateOneID(id int) *ShoppingItemUpdateOne {
	mutation := newShoppingItemMutation(c.config, OpUpdateOne, withShoppingItemID(id))
	return &ShoppingItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ShoppingItem.
func (c *ShoppingItemClient) Delete() *ShoppingItemDelete {
	mutation := newShoppingItemMutation(c.config, OpDelete)
	return &ShoppingItemDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *ShoppingItemClient) DeleteOne(si *ShoppingItem) *ShoppingItemDeleteOne {
	return c.DeleteOneID(si.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *ShoppingItemClient) DeleteOneID(id int) *ShoppingItemDeleteOne {
	builder := c.Delete().Where(shoppingitem.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ShoppingItemDeleteOne{builder}
}

// Query returns a query builder for ShoppingItem.
func (c *ShoppingItemClient) Query() *ShoppingItemQuery {
	return &ShoppingItemQuery{
		config: c.config,
	}
}

// Get returns a ShoppingItem entity by its id.
func (c *ShoppingItemClient) Get(ctx context.Context, id int) (*ShoppingItem, error) {
	return c.Query().Where(shoppingitem.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ShoppingItemClient) GetX(ctx context.Context, id int) *ShoppingItem {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryItem queries the item edge of a ShoppingItem.
func (c *ShoppingItemClient) QueryItem(si *ShoppingItem) *ItemQuery {
	query := &ItemQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := si.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(shoppingitem.Table, shoppingitem.FieldID, id),
			sqlgraph.To(item.Table, item.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, shoppingitem.ItemTable, shoppingitem.ItemColumn),
		)
		fromV = sqlgraph.Neighbors(si.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryShopping queries the shopping edge of a ShoppingItem.
func (c *ShoppingItemClient) QueryShopping(si *ShoppingItem) *ShoppingQuery {
	query := &ShoppingQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := si.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(shoppingitem.Table, shoppingitem.FieldID, id),
			sqlgraph.To(shopping.Table, shopping.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, shoppingitem.ShoppingTable, shoppingitem.ShoppingColumn),
		)
		fromV = sqlgraph.Neighbors(si.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryShoppingList queries the shoppingList edge of a ShoppingItem.
func (c *ShoppingItemClient) QueryShoppingList(si *ShoppingItem) *ShoppingListItemQuery {
	query := &ShoppingListItemQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := si.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(shoppingitem.Table, shoppingitem.FieldID, id),
			sqlgraph.To(shoppinglistitem.Table, shoppinglistitem.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, shoppingitem.ShoppingListTable, shoppingitem.ShoppingListColumn),
		)
		fromV = sqlgraph.Neighbors(si.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ShoppingItemClient) Hooks() []Hook {
	return c.hooks.ShoppingItem
}

// ShoppingListClient is a client for the ShoppingList schema.
type ShoppingListClient struct {
	config
}

// NewShoppingListClient returns a client for the ShoppingList from the given config.
func NewShoppingListClient(c config) *ShoppingListClient {
	return &ShoppingListClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `shoppinglist.Hooks(f(g(h())))`.
func (c *ShoppingListClient) Use(hooks ...Hook) {
	c.hooks.ShoppingList = append(c.hooks.ShoppingList, hooks...)
}

// Create returns a create builder for ShoppingList.
func (c *ShoppingListClient) Create() *ShoppingListCreate {
	mutation := newShoppingListMutation(c.config, OpCreate)
	return &ShoppingListCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ShoppingList entities.
func (c *ShoppingListClient) CreateBulk(builders ...*ShoppingListCreate) *ShoppingListCreateBulk {
	return &ShoppingListCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ShoppingList.
func (c *ShoppingListClient) Update() *ShoppingListUpdate {
	mutation := newShoppingListMutation(c.config, OpUpdate)
	return &ShoppingListUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ShoppingListClient) UpdateOne(sl *ShoppingList) *ShoppingListUpdateOne {
	mutation := newShoppingListMutation(c.config, OpUpdateOne, withShoppingList(sl))
	return &ShoppingListUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ShoppingListClient) UpdateOneID(id int) *ShoppingListUpdateOne {
	mutation := newShoppingListMutation(c.config, OpUpdateOne, withShoppingListID(id))
	return &ShoppingListUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ShoppingList.
func (c *ShoppingListClient) Delete() *ShoppingListDelete {
	mutation := newShoppingListMutation(c.config, OpDelete)
	return &ShoppingListDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *ShoppingListClient) DeleteOne(sl *ShoppingList) *ShoppingListDeleteOne {
	return c.DeleteOneID(sl.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *ShoppingListClient) DeleteOneID(id int) *ShoppingListDeleteOne {
	builder := c.Delete().Where(shoppinglist.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ShoppingListDeleteOne{builder}
}

// Query returns a query builder for ShoppingList.
func (c *ShoppingListClient) Query() *ShoppingListQuery {
	return &ShoppingListQuery{
		config: c.config,
	}
}

// Get returns a ShoppingList entity by its id.
func (c *ShoppingListClient) Get(ctx context.Context, id int) (*ShoppingList, error) {
	return c.Query().Where(shoppinglist.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ShoppingListClient) GetX(ctx context.Context, id int) *ShoppingList {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryItems queries the items edge of a ShoppingList.
func (c *ShoppingListClient) QueryItems(sl *ShoppingList) *ShoppingListItemQuery {
	query := &ShoppingListItemQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := sl.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(shoppinglist.Table, shoppinglist.FieldID, id),
			sqlgraph.To(shoppinglistitem.Table, shoppinglistitem.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, shoppinglist.ItemsTable, shoppinglist.ItemsColumn),
		)
		fromV = sqlgraph.Neighbors(sl.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryPurchases queries the purchases edge of a ShoppingList.
func (c *ShoppingListClient) QueryPurchases(sl *ShoppingList) *ShoppingQuery {
	query := &ShoppingQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := sl.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(shoppinglist.Table, shoppinglist.FieldID, id),
			sqlgraph.To(shopping.Table, shopping.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, shoppinglist.PurchasesTable, shoppinglist.PurchasesColumn),
		)
		fromV = sqlgraph.Neighbors(sl.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ShoppingListClient) Hooks() []Hook {
	return c.hooks.ShoppingList
}

// ShoppingListItemClient is a client for the ShoppingListItem schema.
type ShoppingListItemClient struct {
	config
}

// NewShoppingListItemClient returns a client for the ShoppingListItem from the given config.
func NewShoppingListItemClient(c config) *ShoppingListItemClient {
	return &ShoppingListItemClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `shoppinglistitem.Hooks(f(g(h())))`.
func (c *ShoppingListItemClient) Use(hooks ...Hook) {
	c.hooks.ShoppingListItem = append(c.hooks.ShoppingListItem, hooks...)
}

// Create returns a create builder for ShoppingListItem.
func (c *ShoppingListItemClient) Create() *ShoppingListItemCreate {
	mutation := newShoppingListItemMutation(c.config, OpCreate)
	return &ShoppingListItemCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ShoppingListItem entities.
func (c *ShoppingListItemClient) CreateBulk(builders ...*ShoppingListItemCreate) *ShoppingListItemCreateBulk {
	return &ShoppingListItemCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ShoppingListItem.
func (c *ShoppingListItemClient) Update() *ShoppingListItemUpdate {
	mutation := newShoppingListItemMutation(c.config, OpUpdate)
	return &ShoppingListItemUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ShoppingListItemClient) UpdateOne(sli *ShoppingListItem) *ShoppingListItemUpdateOne {
	mutation := newShoppingListItemMutation(c.config, OpUpdateOne, withShoppingListItem(sli))
	return &ShoppingListItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ShoppingListItemClient) UpdateOneID(id int) *ShoppingListItemUpdateOne {
	mutation := newShoppingListItemMutation(c.config, OpUpdateOne, withShoppingListItemID(id))
	return &ShoppingListItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ShoppingListItem.
func (c *ShoppingListItemClient) Delete() *ShoppingListItemDelete {
	mutation := newShoppingListItemMutation(c.config, OpDelete)
	return &ShoppingListItemDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *ShoppingListItemClient) DeleteOne(sli *ShoppingListItem) *ShoppingListItemDeleteOne {
	return c.DeleteOneID(sli.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *ShoppingListItemClient) DeleteOneID(id int) *ShoppingListItemDeleteOne {
	builder := c.Delete().Where(shoppinglistitem.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ShoppingListItemDeleteOne{builder}
}

// Query returns a query builder for ShoppingListItem.
func (c *ShoppingListItemClient) Query() *ShoppingListItemQuery {
	return &ShoppingListItemQuery{
		config: c.config,
	}
}

// Get returns a ShoppingListItem entity by its id.
func (c *ShoppingListItemClient) Get(ctx context.Context, id int) (*ShoppingListItem, error) {
	return c.Query().Where(shoppinglistitem.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ShoppingListItemClient) GetX(ctx context.Context, id int) *ShoppingListItem {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryShoppingList queries the shoppingList edge of a ShoppingListItem.
func (c *ShoppingListItemClient) QueryShoppingList(sli *ShoppingListItem) *ShoppingListQuery {
	query := &ShoppingListQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := sli.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(shoppinglistitem.Table, shoppinglistitem.FieldID, id),
			sqlgraph.To(shoppinglist.Table, shoppinglist.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, shoppinglistitem.ShoppingListTable, shoppinglistitem.ShoppingListColumn),
		)
		fromV = sqlgraph.Neighbors(sli.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryItem queries the item edge of a ShoppingListItem.
func (c *ShoppingListItemClient) QueryItem(sli *ShoppingListItem) *ItemQuery {
	query := &ItemQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := sli.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(shoppinglistitem.Table, shoppinglistitem.FieldID, id),
			sqlgraph.To(item.Table, item.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, shoppinglistitem.ItemTable, shoppinglistitem.ItemColumn),
		)
		fromV = sqlgraph.Neighbors(sli.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryPurchase queries the purchase edge of a ShoppingListItem.
func (c *ShoppingListItemClient) QueryPurchase(sli *ShoppingListItem) *ShoppingItemQuery {
	query := &ShoppingItemQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := sli.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(shoppinglistitem.Table, shoppinglistitem.FieldID, id),
			sqlgraph.To(shoppingitem.Table, shoppingitem.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, shoppinglistitem.PurchaseTable, shoppinglistitem.PurchaseColumn),
		)
		fromV = sqlgraph.Neighbors(sli.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ShoppingListItemClient) Hooks() []Hook {
	return c.hooks.ShoppingListItem
}

// SubLabelClient is a client for the SubLabel schema.
type SubLabelClient struct {
	config
}

// NewSubLabelClient returns a client for the SubLabel from the given config.
func NewSubLabelClient(c config) *SubLabelClient {
	return &SubLabelClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `sublabel.Hooks(f(g(h())))`.
func (c *SubLabelClient) Use(hooks ...Hook) {
	c.hooks.SubLabel = append(c.hooks.SubLabel, hooks...)
}

// Create returns a create builder for SubLabel.
func (c *SubLabelClient) Create() *SubLabelCreate {
	mutation := newSubLabelMutation(c.config, OpCreate)
	return &SubLabelCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SubLabel entities.
func (c *SubLabelClient) CreateBulk(builders ...*SubLabelCreate) *SubLabelCreateBulk {
	return &SubLabelCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SubLabel.
func (c *SubLabelClient) Update() *SubLabelUpdate {
	mutation := newSubLabelMutation(c.config, OpUpdate)
	return &SubLabelUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SubLabelClient) UpdateOne(sl *SubLabel) *SubLabelUpdateOne {
	mutation := newSubLabelMutation(c.config, OpUpdateOne, withSubLabel(sl))
	return &SubLabelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SubLabelClient) UpdateOneID(id int) *SubLabelUpdateOne {
	mutation := newSubLabelMutation(c.config, OpUpdateOne, withSubLabelID(id))
	return &SubLabelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SubLabel.
func (c *SubLabelClient) Delete() *SubLabelDelete {
	mutation := newSubLabelMutation(c.config, OpDelete)
	return &SubLabelDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *SubLabelClient) DeleteOne(sl *SubLabel) *SubLabelDeleteOne {
	return c.DeleteOneID(sl.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *SubLabelClient) DeleteOneID(id int) *SubLabelDeleteOne {
	builder := c.Delete().Where(sublabel.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SubLabelDeleteOne{builder}
}

// Query returns a query builder for SubLabel.
func (c *SubLabelClient) Query() *SubLabelQuery {
	return &SubLabelQuery{
		config: c.config,
	}
}

// Get returns a SubLabel entity by its id.
func (c *SubLabelClient) Get(ctx context.Context, id int) (*SubLabel, error) {
	return c.Query().Where(sublabel.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SubLabelClient) GetX(ctx context.Context, id int) *SubLabel {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryParent queries the parent edge of a SubLabel.
func (c *SubLabelClient) QueryParent(sl *SubLabel) *TagQuery {
	query := &TagQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := sl.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(sublabel.Table, sublabel.FieldID, id),
			sqlgraph.To(tag.Table, tag.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, sublabel.ParentTable, sublabel.ParentColumn),
		)
		fromV = sqlgraph.Neighbors(sl.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryItems queries the items edge of a SubLabel.
func (c *SubLabelClient) QueryItems(sl *SubLabel) *ItemQuery {
	query := &ItemQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := sl.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(sublabel.Table, sublabel.FieldID, id),
			sqlgraph.To(item.Table, item.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, sublabel.ItemsTable, sublabel.ItemsColumn),
		)
		fromV = sqlgraph.Neighbors(sl.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SubLabelClient) Hooks() []Hook {
	return c.hooks.SubLabel
}

// TagClient is a client for the Tag schema.
type TagClient struct {
	config
}

// NewTagClient returns a client for the Tag from the given config.
func NewTagClient(c config) *TagClient {
	return &TagClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `tag.Hooks(f(g(h())))`.
func (c *TagClient) Use(hooks ...Hook) {
	c.hooks.Tag = append(c.hooks.Tag, hooks...)
}

// Create returns a create builder for Tag.
func (c *TagClient) Create() *TagCreate {
	mutation := newTagMutation(c.config, OpCreate)
	return &TagCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Tag entities.
func (c *TagClient) CreateBulk(builders ...*TagCreate) *TagCreateBulk {
	return &TagCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Tag.
func (c *TagClient) Update() *TagUpdate {
	mutation := newTagMutation(c.config, OpUpdate)
	return &TagUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TagClient) UpdateOne(t *Tag) *TagUpdateOne {
	mutation := newTagMutation(c.config, OpUpdateOne, withTag(t))
	return &TagUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TagClient) UpdateOneID(id int) *TagUpdateOne {
	mutation := newTagMutation(c.config, OpUpdateOne, withTagID(id))
	return &TagUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Tag.
func (c *TagClient) Delete() *TagDelete {
	mutation := newTagMutation(c.config, OpDelete)
	return &TagDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *TagClient) DeleteOne(t *Tag) *TagDeleteOne {
	return c.DeleteOneID(t.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *TagClient) DeleteOneID(id int) *TagDeleteOne {
	builder := c.Delete().Where(tag.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TagDeleteOne{builder}
}

// Query returns a query builder for Tag.
func (c *TagClient) Query() *TagQuery {
	return &TagQuery{
		config: c.config,
	}
}

// Get returns a Tag entity by its id.
func (c *TagClient) Get(ctx context.Context, id int) (*Tag, error) {
	return c.Query().Where(tag.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TagClient) GetX(ctx context.Context, id int) *Tag {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryItems queries the items edge of a Tag.
func (c *TagClient) QueryItems(t *Tag) *ItemQuery {
	query := &ItemQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := t.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tag.Table, tag.FieldID, id),
			sqlgraph.To(item.Table, item.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, tag.ItemsTable, tag.ItemsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(t.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryChildren queries the children edge of a Tag.
func (c *TagClient) QueryChildren(t *Tag) *SubLabelQuery {
	query := &SubLabelQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := t.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tag.Table, tag.FieldID, id),
			sqlgraph.To(sublabel.Table, sublabel.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tag.ChildrenTable, tag.ChildrenColumn),
		)
		fromV = sqlgraph.Neighbors(t.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TagClient) Hooks() []Hook {
	hooks := c.hooks.Tag
	return append(hooks[:len(hooks):len(hooks)], tag.Hooks[:]...)
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Create returns a create builder for User.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(u *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(u))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id int) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *UserClient) DeleteOne(u *User) *UserDeleteOne {
	return c.DeleteOneID(u.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *UserClient) DeleteOneID(id int) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id int) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id int) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryInvites queries the invites edge of a User.
func (c *UserClient) QueryInvites(u *User) *AccountInviteQuery {
	query := &AccountInviteQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(accountinvite.Table, accountinvite.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.InvitesTable, user.InvitesColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryMemberships queries the memberships edge of a User.
func (c *UserClient) QueryMemberships(u *User) *AccountMemberQuery {
	query := &AccountMemberQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(accountmember.Table, accountmember.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.MembershipsTable, user.MembershipsColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// VendorClient is a client for the Vendor schema.
type VendorClient struct {
	config
}

// NewVendorClient returns a client for the Vendor from the given config.
func NewVendorClient(c config) *VendorClient {
	return &VendorClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `vendor.Hooks(f(g(h())))`.
func (c *VendorClient) Use(hooks ...Hook) {
	c.hooks.Vendor = append(c.hooks.Vendor, hooks...)
}

// Create returns a create builder for Vendor.
func (c *VendorClient) Create() *VendorCreate {
	mutation := newVendorMutation(c.config, OpCreate)
	return &VendorCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Vendor entities.
func (c *VendorClient) CreateBulk(builders ...*VendorCreate) *VendorCreateBulk {
	return &VendorCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Vendor.
func (c *VendorClient) Update() *VendorUpdate {
	mutation := newVendorMutation(c.config, OpUpdate)
	return &VendorUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *VendorClient) UpdateOne(v *Vendor) *VendorUpdateOne {
	mutation := newVendorMutation(c.config, OpUpdateOne, withVendor(v))
	return &VendorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *VendorClient) UpdateOneID(id int) *VendorUpdateOne {
	mutation := newVendorMutation(c.config, OpUpdateOne, withVendorID(id))
	return &VendorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Vendor.
func (c *VendorClient) Delete() *VendorDelete {
	mutation := newVendorMutation(c.config, OpDelete)
	return &VendorDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *VendorClient) DeleteOne(v *Vendor) *VendorDeleteOne {
	return c.DeleteOneID(v.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *VendorClient) DeleteOneID(id int) *VendorDeleteOne {
	builder := c.Delete().Where(vendor.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &VendorDeleteOne{builder}
}

// Query returns a query builder for Vendor.
func (c *VendorClient) Query() *VendorQuery {
	return &VendorQuery{
		config: c.config,
	}
}

// Get returns a Vendor entity by its id.
func (c *VendorClient) Get(ctx context.Context, id int) (*Vendor, error) {
	return c.Query().Where(vendor.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *VendorClient) GetX(ctx context.Context, id int) *Vendor {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryPurchases queries the purchases edge of a Vendor.
func (c *VendorClient) QueryPurchases(v *Vendor) *ShoppingQuery {
	query := &ShoppingQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := v.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(vendor.Table, vendor.FieldID, id),
			sqlgraph.To(shopping.Table, shopping.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, vendor.PurchasesTable, vendor.PurchasesColumn),
		)
		fromV = sqlgraph.Neighbors(v.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *VendorClient) Hooks() []Hook {
	return c.hooks.Vendor
}
