// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kingzbauer/shilingi/app-engine/ent/predicate"
	"github.com/kingzbauer/shilingi/app-engine/ent/shoppinglistitem"
)

// ShoppingListItemDelete is the builder for deleting a ShoppingListItem entity.
type ShoppingListItemDelete struct {
	config
	hooks    []Hook
	mutation *ShoppingListItemMutation
}

// Where appends a list predicates to the ShoppingListItemDelete builder.
func (slid *ShoppingListItemDelete) Where(ps ...predicate.ShoppingListItem) *ShoppingListItemDelete {
	slid.mutation.Where(ps...)
	return slid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (slid *ShoppingListItemDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(slid.hooks) == 0 {
		affected, err = slid.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ShoppingListItemMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			slid.mutation = mutation
			affected, err = slid.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(slid.hooks) - 1; i >= 0; i-- {
			if slid.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = slid.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, slid.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (slid *ShoppingListItemDelete) ExecX(ctx context.Context) int {
	n, err := slid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (slid *ShoppingListItemDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: shoppinglistitem.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: shoppinglistitem.FieldID,
			},
		},
	}
	if ps := slid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, slid.driver, _spec)
}

// ShoppingListItemDeleteOne is the builder for deleting a single ShoppingListItem entity.
type ShoppingListItemDeleteOne struct {
	slid *ShoppingListItemDelete
}

// Exec executes the deletion query.
func (slido *ShoppingListItemDeleteOne) Exec(ctx context.Context) error {
	n, err := slido.slid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{shoppinglistitem.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (slido *ShoppingListItemDeleteOne) ExecX(ctx context.Context) {
	slido.slid.ExecX(ctx)
}
