// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kingzbauer/shilingi/app-engine/ent/predicate"
	"github.com/kingzbauer/shilingi/app-engine/ent/shopping"
	"github.com/kingzbauer/shilingi/app-engine/ent/shoppingitem"
	"github.com/kingzbauer/shilingi/app-engine/ent/shoppinglist"
	"github.com/kingzbauer/shilingi/app-engine/ent/vendor"
)

// ShoppingUpdate is the builder for updating Shopping entities.
type ShoppingUpdate struct {
	config
	hooks    []Hook
	mutation *ShoppingMutation
}

// Where appends a list predicates to the ShoppingUpdate builder.
func (su *ShoppingUpdate) Where(ps ...predicate.Shopping) *ShoppingUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetDate sets the "date" field.
func (su *ShoppingUpdate) SetDate(t time.Time) *ShoppingUpdate {
	su.mutation.SetDate(t)
	return su
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (su *ShoppingUpdate) SetNillableDate(t *time.Time) *ShoppingUpdate {
	if t != nil {
		su.SetDate(*t)
	}
	return su
}

// AddItemIDs adds the "items" edge to the ShoppingItem entity by IDs.
func (su *ShoppingUpdate) AddItemIDs(ids ...int) *ShoppingUpdate {
	su.mutation.AddItemIDs(ids...)
	return su
}

// AddItems adds the "items" edges to the ShoppingItem entity.
func (su *ShoppingUpdate) AddItems(s ...*ShoppingItem) *ShoppingUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.AddItemIDs(ids...)
}

// SetVendorID sets the "vendor" edge to the Vendor entity by ID.
func (su *ShoppingUpdate) SetVendorID(id int) *ShoppingUpdate {
	su.mutation.SetVendorID(id)
	return su
}

// SetNillableVendorID sets the "vendor" edge to the Vendor entity by ID if the given value is not nil.
func (su *ShoppingUpdate) SetNillableVendorID(id *int) *ShoppingUpdate {
	if id != nil {
		su = su.SetVendorID(*id)
	}
	return su
}

// SetVendor sets the "vendor" edge to the Vendor entity.
func (su *ShoppingUpdate) SetVendor(v *Vendor) *ShoppingUpdate {
	return su.SetVendorID(v.ID)
}

// AddShoppingListIDs adds the "shoppingList" edge to the ShoppingList entity by IDs.
func (su *ShoppingUpdate) AddShoppingListIDs(ids ...int) *ShoppingUpdate {
	su.mutation.AddShoppingListIDs(ids...)
	return su
}

// AddShoppingList adds the "shoppingList" edges to the ShoppingList entity.
func (su *ShoppingUpdate) AddShoppingList(s ...*ShoppingList) *ShoppingUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.AddShoppingListIDs(ids...)
}

// Mutation returns the ShoppingMutation object of the builder.
func (su *ShoppingUpdate) Mutation() *ShoppingMutation {
	return su.mutation
}

// ClearItems clears all "items" edges to the ShoppingItem entity.
func (su *ShoppingUpdate) ClearItems() *ShoppingUpdate {
	su.mutation.ClearItems()
	return su
}

// RemoveItemIDs removes the "items" edge to ShoppingItem entities by IDs.
func (su *ShoppingUpdate) RemoveItemIDs(ids ...int) *ShoppingUpdate {
	su.mutation.RemoveItemIDs(ids...)
	return su
}

// RemoveItems removes "items" edges to ShoppingItem entities.
func (su *ShoppingUpdate) RemoveItems(s ...*ShoppingItem) *ShoppingUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.RemoveItemIDs(ids...)
}

// ClearVendor clears the "vendor" edge to the Vendor entity.
func (su *ShoppingUpdate) ClearVendor() *ShoppingUpdate {
	su.mutation.ClearVendor()
	return su
}

// ClearShoppingList clears all "shoppingList" edges to the ShoppingList entity.
func (su *ShoppingUpdate) ClearShoppingList() *ShoppingUpdate {
	su.mutation.ClearShoppingList()
	return su
}

// RemoveShoppingListIDs removes the "shoppingList" edge to ShoppingList entities by IDs.
func (su *ShoppingUpdate) RemoveShoppingListIDs(ids ...int) *ShoppingUpdate {
	su.mutation.RemoveShoppingListIDs(ids...)
	return su
}

// RemoveShoppingList removes "shoppingList" edges to ShoppingList entities.
func (su *ShoppingUpdate) RemoveShoppingList(s ...*ShoppingList) *ShoppingUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.RemoveShoppingListIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *ShoppingUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	su.defaults()
	if len(su.hooks) == 0 {
		affected, err = su.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ShoppingMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			su.mutation = mutation
			affected, err = su.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(su.hooks) - 1; i >= 0; i-- {
			if su.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = su.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, su.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (su *ShoppingUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *ShoppingUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *ShoppingUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (su *ShoppingUpdate) defaults() {
	if _, ok := su.mutation.UpdateTime(); !ok {
		v := shopping.UpdateDefaultUpdateTime()
		su.mutation.SetUpdateTime(v)
	}
}

func (su *ShoppingUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   shopping.Table,
			Columns: shopping.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: shopping.FieldID,
			},
		},
	}
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.UpdateTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: shopping.FieldUpdateTime,
		})
	}
	if value, ok := su.mutation.Date(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: shopping.FieldDate,
		})
	}
	if su.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shopping.ItemsTable,
			Columns: []string{shopping.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: shoppingitem.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedItemsIDs(); len(nodes) > 0 && !su.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shopping.ItemsTable,
			Columns: []string{shopping.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: shoppingitem.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shopping.ItemsTable,
			Columns: []string{shopping.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: shoppingitem.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.VendorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shopping.VendorTable,
			Columns: []string{shopping.VendorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: vendor.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.VendorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shopping.VendorTable,
			Columns: []string{shopping.VendorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: vendor.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.ShoppingListCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shopping.ShoppingListTable,
			Columns: []string{shopping.ShoppingListColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: shoppinglist.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedShoppingListIDs(); len(nodes) > 0 && !su.mutation.ShoppingListCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shopping.ShoppingListTable,
			Columns: []string{shopping.ShoppingListColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: shoppinglist.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.ShoppingListIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shopping.ShoppingListTable,
			Columns: []string{shopping.ShoppingListColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: shoppinglist.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{shopping.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// ShoppingUpdateOne is the builder for updating a single Shopping entity.
type ShoppingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ShoppingMutation
}

// SetDate sets the "date" field.
func (suo *ShoppingUpdateOne) SetDate(t time.Time) *ShoppingUpdateOne {
	suo.mutation.SetDate(t)
	return suo
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (suo *ShoppingUpdateOne) SetNillableDate(t *time.Time) *ShoppingUpdateOne {
	if t != nil {
		suo.SetDate(*t)
	}
	return suo
}

// AddItemIDs adds the "items" edge to the ShoppingItem entity by IDs.
func (suo *ShoppingUpdateOne) AddItemIDs(ids ...int) *ShoppingUpdateOne {
	suo.mutation.AddItemIDs(ids...)
	return suo
}

// AddItems adds the "items" edges to the ShoppingItem entity.
func (suo *ShoppingUpdateOne) AddItems(s ...*ShoppingItem) *ShoppingUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.AddItemIDs(ids...)
}

// SetVendorID sets the "vendor" edge to the Vendor entity by ID.
func (suo *ShoppingUpdateOne) SetVendorID(id int) *ShoppingUpdateOne {
	suo.mutation.SetVendorID(id)
	return suo
}

// SetNillableVendorID sets the "vendor" edge to the Vendor entity by ID if the given value is not nil.
func (suo *ShoppingUpdateOne) SetNillableVendorID(id *int) *ShoppingUpdateOne {
	if id != nil {
		suo = suo.SetVendorID(*id)
	}
	return suo
}

// SetVendor sets the "vendor" edge to the Vendor entity.
func (suo *ShoppingUpdateOne) SetVendor(v *Vendor) *ShoppingUpdateOne {
	return suo.SetVendorID(v.ID)
}

// AddShoppingListIDs adds the "shoppingList" edge to the ShoppingList entity by IDs.
func (suo *ShoppingUpdateOne) AddShoppingListIDs(ids ...int) *ShoppingUpdateOne {
	suo.mutation.AddShoppingListIDs(ids...)
	return suo
}

// AddShoppingList adds the "shoppingList" edges to the ShoppingList entity.
func (suo *ShoppingUpdateOne) AddShoppingList(s ...*ShoppingList) *ShoppingUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.AddShoppingListIDs(ids...)
}

// Mutation returns the ShoppingMutation object of the builder.
func (suo *ShoppingUpdateOne) Mutation() *ShoppingMutation {
	return suo.mutation
}

// ClearItems clears all "items" edges to the ShoppingItem entity.
func (suo *ShoppingUpdateOne) ClearItems() *ShoppingUpdateOne {
	suo.mutation.ClearItems()
	return suo
}

// RemoveItemIDs removes the "items" edge to ShoppingItem entities by IDs.
func (suo *ShoppingUpdateOne) RemoveItemIDs(ids ...int) *ShoppingUpdateOne {
	suo.mutation.RemoveItemIDs(ids...)
	return suo
}

// RemoveItems removes "items" edges to ShoppingItem entities.
func (suo *ShoppingUpdateOne) RemoveItems(s ...*ShoppingItem) *ShoppingUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.RemoveItemIDs(ids...)
}

// ClearVendor clears the "vendor" edge to the Vendor entity.
func (suo *ShoppingUpdateOne) ClearVendor() *ShoppingUpdateOne {
	suo.mutation.ClearVendor()
	return suo
}

// ClearShoppingList clears all "shoppingList" edges to the ShoppingList entity.
func (suo *ShoppingUpdateOne) ClearShoppingList() *ShoppingUpdateOne {
	suo.mutation.ClearShoppingList()
	return suo
}

// RemoveShoppingListIDs removes the "shoppingList" edge to ShoppingList entities by IDs.
func (suo *ShoppingUpdateOne) RemoveShoppingListIDs(ids ...int) *ShoppingUpdateOne {
	suo.mutation.RemoveShoppingListIDs(ids...)
	return suo
}

// RemoveShoppingList removes "shoppingList" edges to ShoppingList entities.
func (suo *ShoppingUpdateOne) RemoveShoppingList(s ...*ShoppingList) *ShoppingUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.RemoveShoppingListIDs(ids...)
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *ShoppingUpdateOne) Select(field string, fields ...string) *ShoppingUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Shopping entity.
func (suo *ShoppingUpdateOne) Save(ctx context.Context) (*Shopping, error) {
	var (
		err  error
		node *Shopping
	)
	suo.defaults()
	if len(suo.hooks) == 0 {
		node, err = suo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ShoppingMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			suo.mutation = mutation
			node, err = suo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(suo.hooks) - 1; i >= 0; i-- {
			if suo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = suo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, suo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (suo *ShoppingUpdateOne) SaveX(ctx context.Context) *Shopping {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *ShoppingUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *ShoppingUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (suo *ShoppingUpdateOne) defaults() {
	if _, ok := suo.mutation.UpdateTime(); !ok {
		v := shopping.UpdateDefaultUpdateTime()
		suo.mutation.SetUpdateTime(v)
	}
}

func (suo *ShoppingUpdateOne) sqlSave(ctx context.Context) (_node *Shopping, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   shopping.Table,
			Columns: shopping.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: shopping.FieldID,
			},
		},
	}
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Shopping.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, shopping.FieldID)
		for _, f := range fields {
			if !shopping.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != shopping.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.UpdateTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: shopping.FieldUpdateTime,
		})
	}
	if value, ok := suo.mutation.Date(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: shopping.FieldDate,
		})
	}
	if suo.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shopping.ItemsTable,
			Columns: []string{shopping.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: shoppingitem.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedItemsIDs(); len(nodes) > 0 && !suo.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shopping.ItemsTable,
			Columns: []string{shopping.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: shoppingitem.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shopping.ItemsTable,
			Columns: []string{shopping.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: shoppingitem.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.VendorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shopping.VendorTable,
			Columns: []string{shopping.VendorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: vendor.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.VendorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shopping.VendorTable,
			Columns: []string{shopping.VendorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: vendor.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.ShoppingListCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shopping.ShoppingListTable,
			Columns: []string{shopping.ShoppingListColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: shoppinglist.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedShoppingListIDs(); len(nodes) > 0 && !suo.mutation.ShoppingListCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shopping.ShoppingListTable,
			Columns: []string{shopping.ShoppingListColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: shoppinglist.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.ShoppingListIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shopping.ShoppingListTable,
			Columns: []string{shopping.ShoppingListColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: shoppinglist.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Shopping{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{shopping.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
