// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kingzbauer/shilingi/app-engine/ent/shopping"
	"github.com/kingzbauer/shilingi/app-engine/ent/shoppinglist"
	"github.com/kingzbauer/shilingi/app-engine/ent/shoppinglistitem"
)

// ShoppingListCreate is the builder for creating a ShoppingList entity.
type ShoppingListCreate struct {
	config
	mutation *ShoppingListMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (slc *ShoppingListCreate) SetCreateTime(t time.Time) *ShoppingListCreate {
	slc.mutation.SetCreateTime(t)
	return slc
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (slc *ShoppingListCreate) SetNillableCreateTime(t *time.Time) *ShoppingListCreate {
	if t != nil {
		slc.SetCreateTime(*t)
	}
	return slc
}

// SetUpdateTime sets the "update_time" field.
func (slc *ShoppingListCreate) SetUpdateTime(t time.Time) *ShoppingListCreate {
	slc.mutation.SetUpdateTime(t)
	return slc
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (slc *ShoppingListCreate) SetNillableUpdateTime(t *time.Time) *ShoppingListCreate {
	if t != nil {
		slc.SetUpdateTime(*t)
	}
	return slc
}

// SetName sets the "name" field.
func (slc *ShoppingListCreate) SetName(s string) *ShoppingListCreate {
	slc.mutation.SetName(s)
	return slc
}

// AddItemIDs adds the "items" edge to the ShoppingListItem entity by IDs.
func (slc *ShoppingListCreate) AddItemIDs(ids ...int) *ShoppingListCreate {
	slc.mutation.AddItemIDs(ids...)
	return slc
}

// AddItems adds the "items" edges to the ShoppingListItem entity.
func (slc *ShoppingListCreate) AddItems(s ...*ShoppingListItem) *ShoppingListCreate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return slc.AddItemIDs(ids...)
}

// SetPurchasesID sets the "purchases" edge to the Shopping entity by ID.
func (slc *ShoppingListCreate) SetPurchasesID(id int) *ShoppingListCreate {
	slc.mutation.SetPurchasesID(id)
	return slc
}

// SetNillablePurchasesID sets the "purchases" edge to the Shopping entity by ID if the given value is not nil.
func (slc *ShoppingListCreate) SetNillablePurchasesID(id *int) *ShoppingListCreate {
	if id != nil {
		slc = slc.SetPurchasesID(*id)
	}
	return slc
}

// SetPurchases sets the "purchases" edge to the Shopping entity.
func (slc *ShoppingListCreate) SetPurchases(s *Shopping) *ShoppingListCreate {
	return slc.SetPurchasesID(s.ID)
}

// Mutation returns the ShoppingListMutation object of the builder.
func (slc *ShoppingListCreate) Mutation() *ShoppingListMutation {
	return slc.mutation
}

// Save creates the ShoppingList in the database.
func (slc *ShoppingListCreate) Save(ctx context.Context) (*ShoppingList, error) {
	var (
		err  error
		node *ShoppingList
	)
	slc.defaults()
	if len(slc.hooks) == 0 {
		if err = slc.check(); err != nil {
			return nil, err
		}
		node, err = slc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ShoppingListMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = slc.check(); err != nil {
				return nil, err
			}
			slc.mutation = mutation
			if node, err = slc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(slc.hooks) - 1; i >= 0; i-- {
			if slc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = slc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, slc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (slc *ShoppingListCreate) SaveX(ctx context.Context) *ShoppingList {
	v, err := slc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (slc *ShoppingListCreate) Exec(ctx context.Context) error {
	_, err := slc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (slc *ShoppingListCreate) ExecX(ctx context.Context) {
	if err := slc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (slc *ShoppingListCreate) defaults() {
	if _, ok := slc.mutation.CreateTime(); !ok {
		v := shoppinglist.DefaultCreateTime()
		slc.mutation.SetCreateTime(v)
	}
	if _, ok := slc.mutation.UpdateTime(); !ok {
		v := shoppinglist.DefaultUpdateTime()
		slc.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (slc *ShoppingListCreate) check() error {
	if _, ok := slc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "create_time"`)}
	}
	if _, ok := slc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "update_time"`)}
	}
	if _, ok := slc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "name"`)}
	}
	return nil
}

func (slc *ShoppingListCreate) sqlSave(ctx context.Context) (*ShoppingList, error) {
	_node, _spec := slc.createSpec()
	if err := sqlgraph.CreateNode(ctx, slc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (slc *ShoppingListCreate) createSpec() (*ShoppingList, *sqlgraph.CreateSpec) {
	var (
		_node = &ShoppingList{config: slc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: shoppinglist.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: shoppinglist.FieldID,
			},
		}
	)
	if value, ok := slc.mutation.CreateTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: shoppinglist.FieldCreateTime,
		})
		_node.CreateTime = value
	}
	if value, ok := slc.mutation.UpdateTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: shoppinglist.FieldUpdateTime,
		})
		_node.UpdateTime = value
	}
	if value, ok := slc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: shoppinglist.FieldName,
		})
		_node.Name = value
	}
	if nodes := slc.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shoppinglist.ItemsTable,
			Columns: []string{shoppinglist.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: shoppinglistitem.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := slc.mutation.PurchasesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shoppinglist.PurchasesTable,
			Columns: []string{shoppinglist.PurchasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: shopping.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.shopping_shopping_list = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ShoppingListCreateBulk is the builder for creating many ShoppingList entities in bulk.
type ShoppingListCreateBulk struct {
	config
	builders []*ShoppingListCreate
}

// Save creates the ShoppingList entities in the database.
func (slcb *ShoppingListCreateBulk) Save(ctx context.Context) ([]*ShoppingList, error) {
	specs := make([]*sqlgraph.CreateSpec, len(slcb.builders))
	nodes := make([]*ShoppingList, len(slcb.builders))
	mutators := make([]Mutator, len(slcb.builders))
	for i := range slcb.builders {
		func(i int, root context.Context) {
			builder := slcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ShoppingListMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, slcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, slcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, slcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (slcb *ShoppingListCreateBulk) SaveX(ctx context.Context) []*ShoppingList {
	v, err := slcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (slcb *ShoppingListCreateBulk) Exec(ctx context.Context) error {
	_, err := slcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (slcb *ShoppingListCreateBulk) ExecX(ctx context.Context) {
	if err := slcb.Exec(ctx); err != nil {
		panic(err)
	}
}
